version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6
  node: circleci/node@4.9.0

commands:
  retype-build:
    steps:
      - run:
          name: Run retype build
          command: node_modules/.bin/retype build

jobs:
  deploy-to-s3:
    executor: node/default
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ROLE_ARN: arn:aws:iam::022684377730:role/s3-full-access
      S3_TARGET: s3://doc.hellometaforce.com
    steps:
      - checkout
      - aws-cli/install
      - node/install-packages
      - retype-build
      - run:
          name: deploy to s3
          command: |
            ls
            export AWS_WEB_IDENTITY_TOKEN_FILE="$(mktemp -u)"
            echo $CIRCLE_OIDC_TOKEN > "$AWS_WEB_IDENTITY_TOKEN_FILE"
            aws s3 cp .retype $S3_TARGET --recursive
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-to-s3:
          context: metaforce-aws-context
          filters:
            branches:
              only:
                - main
